### ISSUE TITLE
docker部署，前端显示403

### ISSUE THREAD

**Issue by shiwentao1994** [PidSS/Joi-ShareBoard#2]
![image](https://github.com/user-attachments/assets/be086d57-c7a4-4a42-b114-56f2dd24ae60)
使用docker部署，部署正常，但是前端页面打开显示403
![image](https://github.com/user-attachments/assets/00abc549-2a98-40b2-9343-94de5e44b209)

**Comment by shiwentao1994** [comment]
已创建成功，但是上传10m以上的文件失败

**Comment by PidSS** [comment]
> 已创建成功，但是上传10m以上的文件失败

 @shiwentao1994 可以提供一下部署环境的信息嘛？我没复现出来 🥺 感谢

**Comment by shiwentao1994** [comment]
阿里云ecs服务器 2核2G，  ubuntu22.04  ，使用1panel安装的docker   后续都是使用教程安装

**Comment by shiwentao1994** [comment]
> > 已创建成功，但是上传10m以上的文件失败
> 
> @shiwentao1994 可以提供一下部署环境的信息嘛？我没复现出来 🥺 感谢

在家里的服务器重建了一个，还是上传大文件报错，日志显示如下
![屏幕截图 2024-09-13 220259](https://github.com/user-attachments/assets/840e8af3-6389-4866-bb83-8ea7fae80a05)

**Comment by Swizzzer** [comment]
> > > 已创建成功，但是上传10m以上的文件失败
> > 
> > 
> > @shiwentao1994 可以提供一下部署环境的信息嘛？我没复现出来 🥺 感谢
> 
> 在家里的服务器重建了一个，还是上传大文件报错，日志显示如下 ![屏幕截图 2024-09-13 220259](https://private-user-images.githubusercontent.com/33592118/367325934-840e8af3-6389-4866-bb83-8ea7fae80a05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjcwMjgsIm5iZiI6MTczMjUyNjcyOCwicGF0aCI6Ii8zMzU5MjExOC8zNjczMjU5MzQtODQwZThhZjMtNjM4OS00ODY2LWJiODMtOGVhN2ZhZTgwYTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5MjUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YmI2ZmEwOWM1OWQyMjUxMmU3MjdlMGZhNzg2MDIwMmU4Mjc2MTdlYWI3YjE5NWY3NzdlZDk2MTI2YWI2ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uZe2_4yTmHBZHT6gBOChPT_1KG-QbVn4-PyAIAZm2z0)

nginx默认限制body size导致的。在`nginx_site.conf`文件的`location`项里添加以下配置
```
client_max_body_size 100m;  # 修改为你需要的文件大小
```
然后docker compose up即可。

**Comment by shiwentao1994** [comment]
> > > > 已创建成功，但是上传10m以上的文件失败
> > > 
> > > 
> > > @shiwentao1994 可以提供一下部署环境的信息嘛？我没复现出来 🥺 感谢
> > 
> > 
> > 在家里的服务器重建了一个，还是上传大文件报错，日志显示如下 ![屏幕截图 2024-09-13 220259](https://private-user-images.githubusercontent.com/33592118/367325934-840e8af3-6389-4866-bb83-8ea7fae80a05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjcwMjgsIm5iZiI6MTczMjUyNjcyOCwicGF0aCI6Ii8zMzU5MjExOC8zNjczMjU5MzQtODQwZThhZjMtNjM4OS00ODY2LWJiODMtOGVhN2ZhZTgwYTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5MjUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YmI2ZmEwOWM1OWQyMjUxMmU3MjdlMGZhNzg2MDIwMmU4Mjc2MTdlYWI3YjE5NWY3NzdlZDk2MTI2YWI2ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uZe2_4yTmHBZHT6gBOChPT_1KG-QbVn4-PyAIAZm2z0)
> 
> nginx默认限制body size导致的。在`nginx_site.conf`文件的`location`项里添加以下配置
> 
> ```
> client_max_body_size 100m;  # 修改为你需要的文件大小
> ```
> 
> 然后docker compose up即可。

感谢，我来测试下

**Comment by shiwentao1994** [comment]
已解决
